# Generated by Django 2.0.2 on 2018-03-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('pic', models.ImageField(upload_to='', verbose_name='Фото')),
                ('address', models.CharField(max_length=64, verbose_name='Адрес')),
                ('icon', models.ImageField(upload_to='', verbose_name='Иконка')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('Кафе', models.ImageField(upload_to='')),
            ],
        ),
    ]
