# Generated by Django 2.0.2 on 2018-03-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='Кафе',
            field=models.IntegerField(),
        ),
    ]
