# Generated by Django 2.0.2 on 2018-03-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20180318_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='pic',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
