# Generated by Django 2.0.2 on 2018-03-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180319_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
